version: '3'

services:
    nginx1:
        image: nginx:latest
        volumes:
            - ./nginx/nginx1.conf:/etc/nginx/nginx1.conf
            - ./code:/var/www/html
        ports:
            - "8081:80"
        depends_on:
            - php1
            - db

    nginx2:
        image: nginx:latest
        volumes:
            - ./nginx/nginx2.conf:/etc/nginx/nginx2.conf
            - ./code:/var/www/html
        ports:
            - "8082:80"
        depends_on:
            - php2
            - db

    php1:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./code:/var/www/html
        depends_on:
            - db

    php2:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./code:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "Docker_projet_final"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
