services:
    nginx1:
        image: nginx:latest
        volumes:
            - './nginx/nginx1.conf:/etc/nginx/nginx1.conf'
        ports:
            - "8081:80"
        depends_on:
            - php1

    nginx2:
        image: nginx:latest
        volumes:
            - './nginx/nginx2.conf:/etc/nginx/nginx2.conf'
        ports:
            - "8082:80"
        depends_on:
            - php2

    php1:
        build:
            context: /
            dockerfile: php1/Dockerfile
        volumes:
            - ./php1:/var/www/html

    php2:
        build:
            context: /
            dockerfile: php2/Dockerfile
        volumes:
            - ./php2:/var/www/html

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: Projetfinaldocker
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
