services:
    php1:
        build:
            context: ./
            dockerfile: php1/Dockerfile
        volumes:
            - '.:/var/www/html'
            - './php1/.env:/var/www/html/.env'
        depends_on:
            - db
        networks:
            - ProjetFinal_network

    php2:
        build:
            context: ./
            dockerfile: php2/Dockerfile
        volumes:
            - '.:/var/www/html'
            - './php2/.env:/var/www/html/.env'
        depends_on:
            - db
        networks:
            - ProjetFinal_network

    nginx1:
        image: nginx:latest
        volumes:
            - './nginx/nginx1.conf:/etc/nginx/conf.d/default.conf'
            - '.:/var/www/html'
        ports:
            - "8081:80"
        depends_on:
            - php1
        networks:
            - ProjetFinal_network

    nginx2:
        image: nginx:latest
        volumes:
            - './nginx/nginx2.conf:/etc/nginx/conf.d/default.conf'
            - '.:/var/www/html'
        ports:
            - "8082:80"
        depends_on:
            - php2
        networks:
            - ProjetFinal_network

    reverse-proxy:
        image: nginx:latest
        volumes:
            - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - nginx1
            - nginx2
        networks:
            - ProjetFinal_network


    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: Projetfinaldocker
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - ProjetFinal_network

volumes:
    db_data:

networks:
    ProjetFinal_network:
