version: '3'

services:
    traefik:
        image: traefik:latest
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./traefik.yml:/etc/traefik/traefik.yml" # Configuration Traefik
        networks:
            - ProjetFinal_network

    php1:
        build: ./php1
        volumes:
            - './Laravel:/var/www/html'
            - './php1/.env:/var/www/html/.env'
        depends_on:
            - db
        networks:
            - ProjetFinal_network


    nginx1:
        image: nginx:latest
        volumes:
            - './nginx/nginx1.conf:/etc/nginx/conf.d/default.conf'
            - './Laravel:/var/www/html'
        ports:
            -   "8081:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx1.rule=PathPrefix(`/nginx1`)"
            - "traefik.http.routers.nginx1.middlewares=strip-nginx1@docker"
            - "traefik.http.services.nginx1.loadbalancer.server.port=80"
        depends_on:
            - php1
        networks:
            - ProjetFinal_network

    nginx2:
        image: nginx:latest
        volumes:
            - './nginx/nginx2.conf:/etc/nginx/conf.d/default.conf'
            - './Laravel:/var/www/html'
        ports:
            - "8082:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx2.rule=PathPrefix(`/nginx2`)"
            - "traefik.http.routers.nginx2.middlewares=strip-nginx2@docker"
            - "traefik.http.services.nginx2.loadbalancer.server.port=80"
        networks:
            - ProjetFinal_network

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: Projetfinaldocker
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - ProjetFinal_network

volumes:
    db_data:

networks:
    ProjetFinal_network:
